apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanx-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: kanx.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kanx-api
                port:
                  number: 80
